(* glerp scheme grammar *)

program     = { expression } ;

expression  = literal
            | symbol
            | list
            | vector
            | hash_table
            | quoted
            | quasiquoted
            | unquoted
            | splice
            | syntax_short
            | quasisyntax_short
            | unsyntax_short
            | unsyntax_splice_short
            | interp_string
            | comment ;

(* literals *)

literal     = number | string | boolean ;
number      = [ "-" ] , digit , { digit } , [ "." , digit , { digit } ] ;
string      = '"' , { char } , '"' ;
boolean     = "#t" | "#f" ;

(* symbols *)

symbol      = symbol_char , { symbol_char } ;
symbol_char = letter | digit | "!" | "?" | "-" | "_" | "+"
            | "*" | "/" | "<" | ">" | "=" | "." | ":" | "@"
            | "~" | "^" | "&" | "%" ;

(* delimiters *)

l_delim     = "(" | "[" ;
r_delim     = ")" | "]" ;

(* lists, vectors, and hash tables *)

list        = l_delim , { expression } , [ "." , expression ] , r_delim ;
vector      = "#(" , { expression } , ")" ;
hash_table  = "{" , { expression , expression } , "}" ;

(* quoting *)

quoted      = "'" , expression
            | l_delim , "quote" , expression , r_delim ;

quasiquoted = "`" , expression
            | l_delim , "quasiquote" , expression , r_delim ;

unquoted    = "," , expression
            | l_delim , "unquote" , expression , r_delim ;

splice      = ",@" , expression
            | l_delim , "unquote-splicing" , expression , r_delim ;

(* syntax shorthands *)

syntax_short         = "#'" , expression ;
quasisyntax_short    = "#`" , expression ;
unsyntax_short       = "#," , expression ;
unsyntax_splice_short = "#,@" , expression ;

(* string interpolation *)

interp_string = "$\"" , { interp_segment } , '"' ;
interp_segment = char_no_brace | "{" , expression , "}" ;

(* comments *)

comment     = ";" , { char } ;

(* special forms *)

define      = l_delim , "define" , symbol , expression , r_delim
            | l_delim , "define" , l_delim , symbol , params , r_delim , body , r_delim ;

lambda      = l_delim , "lambda" , ( symbol | l_delim , params , r_delim ) , body , r_delim ;

params      = { symbol } , [ "." , symbol ] ;
body        = expression , { expression } ;

set_bang    = l_delim , "set!" , symbol , expression , r_delim ;

if_form     = l_delim , "if" , expression , expression , [ expression ] , r_delim ;

cond        = l_delim , "cond" , { cond_clause } , r_delim ;
cond_clause = l_delim , expression , body , r_delim
            | l_delim , "else" , body , r_delim ;

case_form   = l_delim , "case" , expression , { case_clause } , r_delim ;
case_clause = l_delim , l_delim , { expression } , r_delim , body , r_delim
            | l_delim , "else" , body , r_delim ;

let         = l_delim , ( "let" | "let*" ) , l_delim , { binding } , r_delim , body , r_delim ;
binding     = l_delim , symbol , expression , r_delim ;

begin       = l_delim , "begin" , { expression } , r_delim ;

and_form    = l_delim , "and" , { expression } , r_delim ;
or_form     = l_delim , "or"  , { expression } , r_delim ;

do_form     = l_delim , "do"
                , l_delim , { do_binding } , r_delim
                , l_delim , expression , { expression } , r_delim
                , { expression }
              , r_delim ;
do_binding  = l_delim , symbol , expression , expression , r_delim ;

define_values = l_delim , "define-values" , l_delim , { symbol } , r_delim , expression , r_delim ;

(* macros: syntax-rules *)

define_syntax = l_delim , "define-syntax" , symbol , ( syntax_rules | transformer ) , r_delim ;

syntax_rules  = l_delim , "syntax-rules" , l_delim , { symbol } , r_delim
                  , { l_delim , pattern , template , r_delim }
                , r_delim ;

pattern       = expression ;
template      = expression ;

(* macros: syntax-case *)

transformer   = l_delim , "lambda" , l_delim , symbol , r_delim , body , r_delim ;

syntax_case   = l_delim , "syntax-case" , expression , l_delim , { symbol } , r_delim
                  , { syntax_clause }
                , r_delim ;
syntax_clause = l_delim , pattern , body , r_delim
              | l_delim , pattern , fender , body , r_delim ;
fender        = expression ;

syntax_form   = l_delim , "syntax" , template , r_delim
              | "#'" , template ;

quasisyntax_form = l_delim , "quasisyntax" , qs_template , r_delim
                 | "#`" , qs_template ;
qs_template      = qs_atom | qs_list ;
qs_atom          = expression ;
qs_list          = l_delim , { qs_element } , r_delim ;
qs_element       = unsyntax_form | unsyntax_splice_form | qs_template ;

unsyntax_form    = l_delim , "unsyntax" , expression , r_delim
                 | "#," , expression ;
unsyntax_splice_form = l_delim , "unsyntax-splicing" , expression , r_delim
                     | "#,@" , expression ;

with_syntax   = l_delim , "with-syntax" , l_delim , { ws_binding } , r_delim , body , r_delim ;
ws_binding    = l_delim , pattern , expression , r_delim ;

(* libraries *)

import_form = l_delim , "import" , { import_spec } , r_delim ;
import_spec = lib_path
            | l_delim , "only" , lib_path , symbol , { symbol } , r_delim ;
lib_path    = ":" , symbol , "/" , symbol , { "/" , symbol }
            | "./" , symbol , { "/" , symbol } ;

export_form = l_delim , "export" , ( "#t" | symbol , { symbol } ) , r_delim ;

(* procedure call *)

call        = l_delim , expression , { expression } , r_delim ;

(* terminals *)

letter        = "a" | ... | "z" | "A" | ... | "Z" ;
digit         = "0" | ... | "9" ;
char          = ? any character ? ;
char_no_brace = ? any character except { and } ? ;
