name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: nix-community
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: activate-nix
        run: nix develop ".#ci" --print-build-logs --command bash -c 'cat >>"$GITHUB_PATH" <<<"$PATH"'
      - run: task vet
      - run: task test
      - run: task lint
      - run: task build
        if: ${{ success() }}
